version: 0.2
phases:
  pre_build:
    commands:
      - cd terraform
      - cd infrastructure
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform apply --auto-approve
      